#!/usr/bin/env python3
"""Download self-hosted Fontsource woff2 into assets/fonts/ and write fonts.css.

Prefers `npm pack` when npm is available; otherwise downloads from jsDelivr.

jsDelivr fallback URLs (pinned versions):
  https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.2.8/files/noto-serif-sc-chinese-simplified-400-normal.woff2
  https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.2.8/files/noto-serif-sc-latin-400-normal.woff2
  https://cdn.jsdelivr.net/npm/@fontsource/source-serif-4@5.2.8/files/source-serif-4-latin-400-normal.woff2
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "assets" / "fonts"

PACKAGES = (
    "@fontsource/noto-serif-sc",
    "@fontsource/source-serif-4",
)

# Prefer chinese-simplified for body CJK; keep latin for Source Serif 4 + Noto latin.
TARGET_FILES = (
    "noto-serif-sc-chinese-simplified-400-normal.woff2",
    "noto-serif-sc-latin-400-normal.woff2",
    "source-serif-4-latin-400-normal.woff2",
)

JSDELIVR = {
    "noto-serif-sc-chinese-simplified-400-normal.woff2": (
        "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.2.8/"
        "files/noto-serif-sc-chinese-simplified-400-normal.woff2"
    ),
    "noto-serif-sc-latin-400-normal.woff2": (
        "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.2.8/"
        "files/noto-serif-sc-latin-400-normal.woff2"
    ),
    "source-serif-4-latin-400-normal.woff2": (
        "https://cdn.jsdelivr.net/npm/@fontsource/source-serif-4@5.2.8/"
        "files/source-serif-4-latin-400-normal.woff2"
    ),
}

FONTS_CSS = """\
/* Self-hosted Fontsource — generated by scripts/vendor_fonts.py */
@font-face {
  font-family: "Noto Serif SC";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url("./noto-serif-sc-chinese-simplified-400-normal.woff2") format("woff2");
  unicode-range: U+4E00-9FFF, U+3400-4DBF, U+F900-FAFF, U+2E80-2EFF, U+3000-303F, U+FF00-FFEF;
}

@font-face {
  font-family: "Noto Serif SC";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url("./noto-serif-sc-latin-400-normal.woff2") format("woff2");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
    U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215,
    U+FEFF, U+FFFD;
}

@font-face {
  font-family: "Source Serif 4";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url("./source-serif-4-latin-400-normal.woff2") format("woff2");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
    U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215,
    U+FEFF, U+FFFD;
}
"""


def npm_executable() -> str | None:
    """Resolve npm binary; on Windows prefer npm.cmd for CreateProcess."""
    if sys.platform == "win32":
        return shutil.which("npm.cmd") or shutil.which("npm")
    return shutil.which("npm")


def copy_woff2_from_extract(extract_root: Path, dest: Path) -> list[str]:
    """Find and copy target woff2 files from extracted npm pack trees."""
    found: list[str] = []
    for name in TARGET_FILES:
        matches = list(extract_root.rglob(name))
        if not matches:
            continue
        shutil.copy2(matches[0], dest / name)
        found.append(name)
    return found


def vendor_via_npm(dest: Path, npm_bin: str) -> list[str]:
    with tempfile.TemporaryDirectory(prefix="pulse-fonts-") as tmp:
        tmp_path = Path(tmp)
        cmd = [npm_bin, "pack", *PACKAGES, "--pack-destination", str(tmp_path)]
        print(f"Running: {' '.join(cmd)}", flush=True)
        proc = subprocess.run(cmd, cwd=tmp_path, capture_output=True, text=True)
        if proc.returncode != 0:
            raise RuntimeError(
                f"npm pack failed ({proc.returncode}):\n{proc.stderr or proc.stdout}"
            )

        extract_root = tmp_path / "extracted"
        extract_root.mkdir()
        for tgz in tmp_path.glob("*.tgz"):
            with tarfile.open(tgz, "r:gz") as tar:
                tar.extractall(extract_root / tgz.stem)

        found = copy_woff2_from_extract(extract_root, dest)
        missing = [n for n in TARGET_FILES if n not in found]
        if missing:
            raise RuntimeError(f"npm pack succeeded but missing woff2: {missing}")
        return found


def vendor_via_jsdelivr(dest: Path) -> list[str]:
    found: list[str] = []
    for name, url in JSDELIVR.items():
        out = dest / name
        print(f"Downloading {url}", flush=True)
        try:
            urllib.request.urlretrieve(url, out)
        except urllib.error.URLError as exc:
            raise RuntimeError(f"Failed to download {url}: {exc}") from exc
        if out.stat().st_size < 1000:
            raise RuntimeError(f"Downloaded file looks too small: {out}")
        found.append(name)
    return found


def write_fonts_css(dest: Path) -> None:
    (dest / "fonts.css").write_text(FONTS_CSS, encoding="utf-8")


def main() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    # Keep directory in git even before fonts land
    (FONTS_DIR / ".gitkeep").touch(exist_ok=True)

    npm_bin = npm_executable()
    try:
        if npm_bin:
            try:
                found = vendor_via_npm(FONTS_DIR, npm_bin)
                print(f"Vendored via npm: {', '.join(found)}")
            except Exception as npm_exc:
                print(f"npm path failed ({npm_exc}); falling back to jsDelivr…", flush=True)
                found = vendor_via_jsdelivr(FONTS_DIR)
                print(f"Vendored via jsDelivr: {', '.join(found)}")
        else:
            print("npm not found; using jsDelivr fallback…", flush=True)
            found = vendor_via_jsdelivr(FONTS_DIR)
            print(f"Vendored via jsDelivr: {', '.join(found)}")
    except Exception as exc:
        print(f"ERROR: could not vendor fonts: {exc}", file=sys.stderr)
        return 1

    write_fonts_css(FONTS_DIR)
    print(f"Wrote {FONTS_DIR / 'fonts.css'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
